# Source: cilium
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubble-relay
  namespace: cilium
  labels:
    k8s-app: hubble-relay
    app.kubernetes.io/name: hubble-relay
    app.kubernetes.io/part-of: cilium
  annotations:
    noa.re/deploy-id: 59220790755d6302
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: hubble-relay
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations: null
      labels:
        k8s-app: hubble-relay
        app.kubernetes.io/name: hubble-relay
        app.kubernetes.io/part-of: cilium
    spec:
      securityContext:
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: hubble-relay
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
        image: quay.io/cilium/hubble-relay:v1.19.4@sha256:59af8c0d561e560c2a042e7600a3496bc0367df8fbf868aa68d5834c8ec1a431
        imagePullPolicy: IfNotPresent
        command:
        - hubble-relay
        args:
        - serve
        ports:
        - name: grpc
          containerPort: 4245
        readinessProbe:
          grpc:
            port: 4222
          timeoutSeconds: 3
        livenessProbe:
          grpc:
            port: 4222
          timeoutSeconds: 10
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 12
        startupProbe:
          grpc:
            port: 4222
          initialDelaySeconds: 10
          failureThreshold: 20
          periodSeconds: 3
        volumeMounts:
        - name: config
          mountPath: /etc/hubble-relay
          readOnly: true
        - name: tls
          mountPath: /var/lib/hubble-relay/tls
          readOnly: true
        terminationMessagePolicy: FallbackToLogsOnError
      restartPolicy: Always
      priorityClassName: null
      serviceAccountName: hubble-relay
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 1
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                k8s-app: cilium
            topologyKey: kubernetes.io/hostname
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - name: config
        configMap:
          name: hubble-relay-config
          items:
          - key: config.yaml
            path: config.yaml
      - name: tls
        projected:
          defaultMode: 256
          sources:
          - secret:
              name: hubble-relay-client-certs
              items:
              - key: tls.crt
                path: client.crt
              - key: tls.key
                path: client.key
              - key: ca.crt
                path: hubble-server-ca.crt
