# Source: idcat
apiVersion: v1
kind: ConfigMap
metadata:
  name: idcat-config
  namespace: idcat
data:
  idcat.toml: |
    bind_address = "0.0.0.0:8080"
    key_source = "kms"

    [authentication]
    audience = "idcat"
    issuer = "https://oidc.eks.eu-west-2.amazonaws.com/id/058FE1E454B013230972F274A3EA3AA7"

    [[github_app]]
    name = "SwigApp"
    app_id = 3543557
    secret_key = "swigapp"

    [[installation]]
    github_app = "SwigApp"
    required_claims = { "sub" = "system:serviceaccount:default:default" }
