# Source: idcat
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idcat
  labels:
    app: idcat
  namespace: idcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idcat
  template:
    metadata:
      labels:
        app: idcat
      annotations:
        checksum/config: ec5c7dd77f48c1f57324b0a860106b6a1a54f5d3d4290620023486c19cb2c7fa
    spec:
      serviceAccountName: idcat
      containers:
      - name: idcat
        image: nresare/idcat:latest
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: idcat-config
          mountPath: /config
      volumes:
      - name: idcat-config
        configMap:
          name: idcat-config
