# Source: idcat
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idcat
  labels:
    app: idcat
  namespace: idcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idcat
  template:
    metadata:
      labels:
        app: idcat
      annotations:
        checksum/config: 0d2539e4c697623aa900fbaa8720abbfe8cd129ff6ede32205c220d1d6b74ff8
    spec:
      serviceAccountName: idcat
      containers:
      - name: idcat
        image: nresare/idcat:latest
        volumeMounts:
        - name: idcat-config
          mountPath: /config
      volumes:
      - name: idcat-config
        configMap:
          name: idcat-config
