# Source: idcat
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idcat
  labels:
    app: idcat
  namespace: idcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idcat
  template:
    metadata:
      labels:
        app: idcat
      annotations:
        checksum/config: 07421389a9064593e855a00e881472000c4cb3889d01ef944c221dc159d1786a
    spec:
      serviceAccountName: idcat
      containers:
      - name: idcat
        image: nresare/idcat:latest
        volumeMounts:
        - name: idcat-config
          mountPath: /config
      volumes:
      - name: idcat-config
        configMap:
          name: idcat-config
