# Source: aws-load-balancer-controller
apiVersion: v1
kind: List
metadata:
  name: ingress-class
  namespace: kube-system
items:
- apiVersion: elbv2.k8s.aws/v1beta1
  kind: IngressClassParams
  metadata:
    name: alb
    labels:
      app.kubernetes.io/managed-by: Helm
      helm.sh/chart: aws-load-balancer-controller-3.1.0
      app.kubernetes.io/name: aws-load-balancer-controller
      app.kubernetes.io/instance: aws-load-balancer-controller
      app.kubernetes.io/version: v3.1.0
- apiVersion: networking.k8s.io/v1
  kind: IngressClass
  metadata:
    name: alb
    labels:
      app.kubernetes.io/managed-by: Helm
      helm.sh/chart: aws-load-balancer-controller-3.1.0
      app.kubernetes.io/name: aws-load-balancer-controller
      app.kubernetes.io/instance: aws-load-balancer-controller
      app.kubernetes.io/version: v3.1.0
  spec:
    controller: ingress.k8s.aws/alb
