# Source: karpenter
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: karpenter-dns
  namespace: kube-system
  labels:
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/version: 1.12.1
  annotations:
    noa.re/deploy-id: d15a73d9723e4e62
rules:
- apiGroups:
  - ''
  resources:
  - services
  resourceNames:
  - kube-dns
  verbs:
  - get
