# Source: aws-load-balancer-controller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::658786808637:role/test0/aws-load-balancer-controller
automountServiceAccountToken: true
