# Source: karpenter
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: karpenter
  namespace: karpenter
  labels:
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/version: 1.12.1
  annotations:
    noa.re/deploy-id: d15a73d9723e4e62
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: karpenter
subjects:
- kind: ServiceAccount
  name: karpenter
  namespace: karpenter
