# Source: teleport-cluster
apiVersion: v1
kind: Service
metadata:
  name: teleport-cluster
  namespace: teleport-cluster
  labels:
    app.kubernetes.io/name: teleport-cluster
    app.kubernetes.io/instance: teleport-cluster
    app.kubernetes.io/component: proxy
    app.kubernetes.io/version: 18.7.3
    teleport.dev/majorVersion: '18'
  annotations:
    external-dns.alpha.kubernetes.io/hostname: '*.test0.aws.noa.re,test0.aws.noa.re'
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTPS
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
  - name: tls
    port: 443
    targetPort: 3080
    protocol: TCP
  selector:
    app.kubernetes.io/name: teleport-cluster
    app.kubernetes.io/instance: teleport-cluster
    app.kubernetes.io/component: proxy
