# Source: teleport-cluster
apiVersion: resources.teleport.dev/v2
kind: TeleportProvisionToken
metadata:
  name: kubernetes-token
  labels:
    teleport.dev/origin: dynamic
  namespace: teleport-cluster
spec:
  roles:
  - App
  - Discovery
  join_method: kubernetes
  kubernetes:
    type: in_cluster
    allow:
    - service_account: teleport:teleport-kube-agent
