# Source: external-dns
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::658786808637:role/test0-external-dns
automountServiceAccountToken: true
